const emojis = [
  {
    id: 1,
    emoji: "😀",
    description: "Grinning Face",
    score: 5,
    tooltip: "Very happy and joyful",
  },
  {
    id: 2,
    emoji: "😃",
    description: "Grinning Face with Big Eyes",
    score: 5,
    tooltip: "Very happy and joyful",
  },
  {
    id: 3,
    emoji: "😄",
    description: "Grinning Face with Smiling Eyes",
    score: 5,
    tooltip: "Very happy and joyful",
  },
  {
    id: 4,
    emoji: "😁",
    description: "Beaming Face with Smiling Eyes",
    score: 5,
    tooltip: "Very happy and joyful",
  },
  {
    id: 5,
    emoji: "😆",
    description: "Grinning Squinting Face",
    score: 5,
    tooltip: "Very happy and joyful",
  },
  {
    id: 6,
    emoji: "😅",
    description: "Grinning Face with Sweat",
    score: 4,
    tooltip: "Nervous but positive",
  },
  {
    id: 7,
    emoji: "🤣",
    description: "Rolling on the Floor Laughing",
    score: 5,
    tooltip: "Extremely happy and amused",
  },
  {
    id: 8,
    emoji: "😂",
    description: "Face with Tears of Joy",
    score: 5,
    tooltip: "Extremely happy and amused",
  },
  {
    id: 9,
    emoji: "🙂",
    description: "Slightly Smiling Face",
    score: 3,
    tooltip: "Mildly happy or content",
  },
  {
    id: 10,
    emoji: "🙃",
    description: "Upside-Down Face",
    score: 1,
    tooltip: "Playful, slightly ambiguous",
  },
  {
    id: 11,
    emoji: "😉",
    description: "Winking Face",
    score: 3,
    tooltip: "Playful or friendly",
  },
  {
    id: 12,
    emoji: "😊",
    description: "Smiling Face with Smiling Eyes",
    score: 4,
    tooltip: "Happy and content",
  },
  {
    id: 13,
    emoji: "😇",
    description: "Smiling Face with Halo",
    score: 4,
    tooltip: "Innocent or pure",
  },
  {
    id: 14,
    emoji: "🥰",
    description: "Smiling Face with Hearts",
    score: 5,
    tooltip: "Loved and affectionate",
  },
  {
    id: 15,
    emoji: "😍",
    description: "Heart Eyes",
    score: 5,
    tooltip: "In love or admiration",
  },
  {
    id: 16,
    emoji: "🤩",
    description: "Star-Struck",
    score: 5,
    tooltip: "Excited and amazed",
  },
  {
    id: 17,
    emoji: "😘",
    description: "Face Blowing a Kiss",
    score: 4,
    tooltip: "Affectionate or loving",
  },
  {
    id: 18,
    emoji: "😗",
    description: "Kissing Face",
    score: 3,
    tooltip: "Affectionate",
  },
  {
    id: 19,
    emoji: "😚",
    description: "Kissing Face with Closed Eyes",
    score: 4,
    tooltip: "Affectionate and content",
  },
  {
    id: 20,
    emoji: "😙",
    description: "Kissing Face with Smiling Eyes",
    score: 4,
    tooltip: "Affectionate and happy",
  },
  {
    id: 21,
    emoji: "🥲",
    description: "Smiling Through Tears",
    score: 1,
    tooltip: "Bittersweet or emotional",
  },
  {
    id: 22,
    emoji: "😋",
    description: "Face Savoring Food",
    score: 3,
    tooltip: "Happy or satisfied",
  },
  {
    id: 23,
    emoji: "😛",
    description: "Face with Tongue",
    score: 2,
    tooltip: "Playful or silly",
  },
  {
    id: 24,
    emoji: "😜",
    description: "Winking Face with Tongue",
    score: 2,
    tooltip: "Playful and silly",
  },
  {
    id: 25,
    emoji: "🤪",
    description: "Zany Face",
    score: 3,
    tooltip: "Crazy fun or goofy",
  },
  {
    id: 26,
    emoji: "😝",
    description: "Squinting Face with Tongue",
    score: 2,
    tooltip: "Playful and silly",
  },
  {
    id: 27,
    emoji: "🤑",
    description: "Money-Mouth Face",
    score: 1,
    tooltip: "Excited or greedy",
  },
  {
    id: 28,
    emoji: "🤗",
    description: "Hugging Face",
    score: 4,
    tooltip: "Friendly and loving",
  },
  {
    id: 29,
    emoji: "🤭",
    description: "Face with Hand Over Mouth",
    score: 1,
    tooltip: "Embarrassed or shy",
  },
  {
    id: 30,
    emoji: "🫢",
    description: "Face with Open Eyes and Hand Over Mouth",
    score: 0,
    tooltip: "Surprised or neutral",
  },
  {
    id: 31,
    emoji: "🫣",
    description: "Peeking Face",
    score: 0,
    tooltip: "Curious or anxious",
  },
  {
    id: 32,
    emoji: "🤫",
    description: "Shushing Face",
    score: 0,
    tooltip: "Quiet or secretive",
  },
  {
    id: 33,
    emoji: "🤔",
    description: "Thinking Face",
    score: 0,
    tooltip: "Thinking or unsure",
  },
  {
    id: 34,
    emoji: "🫡",
    description: "Saluting Face",
    score: 2,
    tooltip: "Respectful or positive",
  },
  {
    id: 35,
    emoji: "🤐",
    description: "Zipper-Mouth Face",
    score: -1,
    tooltip: "Reserved or silent",
  },
  {
    id: 36,
    emoji: "🤨",
    description: "Face with Raised Eyebrow",
    score: -1,
    tooltip: "Skeptical or doubtful",
  },
  {
    id: 37,
    emoji: "😐",
    description: "Neutral Face",
    score: 0,
    tooltip: "Neutral or indifferent",
  },
  {
    id: 38,
    emoji: "😑",
    description: "Expressionless Face",
    score: -1,
    tooltip: "Bored or unimpressed",
  },
  {
    id: 39,
    emoji: "😶",
    description: "Face Without Mouth",
    score: 0,
    tooltip: "Silent or neutral",
  },
  {
    id: 40,
    emoji: "🫥",
    description: "Dotted Line Face",
    score: -1,
    tooltip: "Feeling invisible or ignored",
  },
  {
    id: 41,
    emoji: "😶‍🌫️",
    description: "Face in Clouds",
    score: -1,
    tooltip: "Confused or dreamy",
  },
  {
    id: 42,
    emoji: "😏",
    description: "Smirking Face",
    score: 0,
    tooltip: "Smug or sly",
  },
  {
    id: 43,
    emoji: "😒",
    description: "Unamused Face",
    score: -2,
    tooltip: "Unhappy or annoyed",
  },
  {
    id: 44,
    emoji: "🙄",
    description: "Face with Rolling Eyes",
    score: -2,
    tooltip: "Frustrated or annoyed",
  },
  {
    id: 45,
    emoji: "😬",
    description: "Grimacing Face",
    score: -2,
    tooltip: "Awkward or tense",
  },
  {
    id: 46,
    emoji: "😮‍💨",
    description: "Face Exhaling",
    score: -1,
    tooltip: "Relieved or tired",
  },
  {
    id: 47,
    emoji: "🤥",
    description: "Lying Face",
    score: -3,
    tooltip: "Dishonest or negative",
  },
  {
    id: 48,
    emoji: "😌",
    description: "Relieved Face",
    score: 3,
    tooltip: "Calm and content",
  },
  {
    id: 49,
    emoji: "😔",
    description: "Pensive Face",
    score: -2,
    tooltip: "Sad or thoughtful",
  },
  {
    id: 50,
    emoji: "😪",
    description: "Sleepy Face",
    score: -1,
    tooltip: "Tired or sleepy",
  },
  {
    id: 51,
    emoji: "🤤",
    description: "Drooling Face",
    score: 1,
    tooltip: "Desiring or sleepy",
  },
  {
    id: 52,
    emoji: "😴",
    description: "Sleeping Face",
    score: -1,
    tooltip: "Sleeping or tired",
  },
  {
    id: 53,
    emoji: "😷",
    description: "Face with Medical Mask",
    score: -2,
    tooltip: "Sick or cautious",
  },
  {
    id: 54,
    emoji: "🤒",
    description: "Face with Thermometer",
    score: -3,
    tooltip: "Very sick or unwell",
  },
  {
    id: 55,
    emoji: "🤕",
    description: "Face with Head-Bandage",
    score: -3,
    tooltip: "Injured or unwell",
  },
  {
    id: 56,
    emoji: "🤢",
    description: "Nauseated Face",
    score: -3,
    tooltip: "Feeling sick or disgusted",
  },
  {
    id: 57,
    emoji: "🤮",
    description: "Face Vomiting",
    score: -3,
    tooltip: "Very sick or disgusted",
  },
  {
    id: 58,
    emoji: "🥴",
    description: "Woozy Face",
    score: -2,
    tooltip: "Dizzy or disoriented",
  },
  {
    id: 59,
    emoji: "😵",
    description: "Dizzy Face",
    score: -2,
    tooltip: "Dizzy or overwhelmed",
  },
  {
    id: 60,
    emoji: "😵‍💫",
    description: "Face with Spiral Eyes",
    score: -3,
    tooltip: "Very dizzy or confused",
  },
  {
    id: 61,
    emoji: "🥵",
    description: "Hot Face",
    score: -2,
    tooltip: "Overheated or uncomfortable",
  },
  {
    id: 62,
    emoji: "🥶",
    description: "Cold Face",
    score: -2,
    tooltip: "Cold or uncomfortable",
  },
  {
    id: 63,
    emoji: "😶‍🌫️",
    description: "Foggy Face",
    score: -2,
    tooltip: "Confused or cloudy-headed",
  },
  {
    id: 64,
    emoji: "😳",
    description: "Flushed Face",
    score: -1,
    tooltip: "Embarrassed or shocked",
  },
  {
    id: 65,
    emoji: "🥺",
    description: "Pleading Face",
    score: -2,
    tooltip: "Sad or begging",
  },
  {
    id: 66,
    emoji: "😟",
    description: "Worried Face",
    score: -2,
    tooltip: "Worried or anxious",
  },
  {
    id: 67,
    emoji: "😢",
    description: "Crying Face",
    score: -3,
    tooltip: "Sad or upset",
  },
  {
    id: 68,
    emoji: "😭",
    description: "Loudly Crying Face",
    score: -3,
    tooltip: "Very sad or distressed",
  },
  {
    id: 69,
    emoji: "😤",
    description: "Face with Steam From Nose",
    score: -2,
    tooltip: "Frustrated or angry",
  },
  {
    id: 70,
    emoji: "😠",
    description: "Angry Face",
    score: -3,
    tooltip: "Angry or upset",
  },
  {
    id: 71,
    emoji: "😡",
    description: "Pouting Face",
    score: -3,
    tooltip: "Very angry or upset",
  },
  {
    id: 72,
    emoji: "🤬",
    description: "Face with Symbols on Mouth",
    score: -3,
    tooltip: "Extremely angry or cursing",
  },
  {
    id: 73,
    emoji: "😈",
    description: "Smiling Face with Horns",
    score: -2,
    tooltip: "Mischievous or naughty",
  },
  {
    id: 74,
    emoji: "👿",
    description: "Angry Face with Horns",
    score: -3,
    tooltip: "Very angry or evil",
  },
  {
    id: 75,
    emoji: "💀",
    description: "Skull",
    score: -3,
    tooltip: "Death or danger",
  },
  {
    id: 76,
    emoji: "☠️",
    description: "Skull and Crossbones",
    score: -3,
    tooltip: "Danger or toxicity",
  },
  {
    id: 77,
    emoji: "💩",
    description: "Pile of Poo",
    score: -3,
    tooltip: "Disgust or bad mood",
  },
  {
    id: 78,
    emoji: "🤡",
    description: "Clown Face",
    score: -1,
    tooltip: "Silly or foolish",
  },
  {
    id: 79,
    emoji: "👻",
    description: "Ghost",
    score: 0,
    tooltip: "Neutral or spooky",
  },
  {
    id: 80,
    emoji: "😺",
    description: "Grinning Cat Face",
    score: 4,
    tooltip: "Happy and playful",
  },
];

export default emojis;
